# Numpy 기초

> 행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리 할 수 있도록 지원   
> 데이터 구조 뿐 아니라 고성능의 수치 계산 함수를 제공

## 1. 개요
### 1.1 용어
- Scalar : 숫자
- Vector : 숫자들의 1차원 배열 (리스트)
- Matrix : 숫자들의 2차원 배열 (행렬)

### 1.2 list vs ndarray
- list
    - 사용되는 메모리량이 많다.
    - 서로 다른 타입의 데이터를 담을 수 있다.
- ndarray
    - 메모리량이 상대적으로 작다.
    - 서로 다른 타입의 데이터를 담을 수 없다.
    - 내부 반복문을 사용해서 속도가 빠르다.

### 1.3 넘파이를 사용하는 이유
- 넘파이를 사용하지 않고 행렬 연산을 할 경우 반복문을 사용해야 하며 코드가 길어진다.

In [4]:
# 행렬과 스칼라의 연산

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        matrix[i][j] *= 2

matrix

[[2, 4, 6], [8, 10, 12], [14, 16, 18]]

In [5]:
# 행렬끼리의 연산

matrix_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_2 = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

for i in range(len(matrix_1)):
    for j in range(len(matrix_1[0])):
        matrix_1[i][j] += matrix_2[i][j]

matrix_1

[[2, 3, 4], [6, 7, 8], [10, 11, 12]]

- 넘파이를 사용하면 간단하게 행렬 연산을 처리할 수 있다.

In [8]:
# 넘파이 라이브러리를 호출한다
import numpy as np

matrix_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_2 = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

a = np.array(matrix_1)
b = np.array(matrix_2)

In [9]:
a+b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [10]:
a*b

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

---

## 2. 차원

- shape : 행렬의 형태 확인 
- size : 전체 원소의 갯수
- ndim : 행렬의 차원

In [12]:
import numpy as np

a = np.array(1)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
d = np.array([[[1, 2], [1, 2], [1, 2]], [[1, 2], [1, 2], [1, 2]]])

print(a.shape, a.size, a.ndim) # 0차원
print(b.shape, b.size, b.ndim) # 1차원
print(c.shape, c.size, c.ndim) # 2차원
print(d.shape, d.size, d.ndim) # 3차원

() 1 0
(3,) 3 1
(3, 3) 9 2
(2, 3, 2) 12 3


In [219]:
# 행 방향
axis = 0

# 열 방향
axis = 1

# 채널 방향
axis = 2

---

## 3. 넘파이 자료형

> 1. int(8bit, 16bit, 32bit, 64bit) i1, i2, i4, i8 : 정수형, 부호가 있음
> 2. unit(8bit, 16bit, 32bit, 64bit) u1, u2, u4, u8 : 정수형, 부호가 없음
> 3. float(16bit, 32bit, 64bit, 128bit) f2, f4, f8, f16 : 실수형, 부호가 있음
> 4. 복소수형
>   - complex64 : 두개의 32비트 부동 소수점으로 표시되는 복소수 c8
>   - complex128 : 두개의 64비트 부동소수점으로 표시되는 복소수 c16
> 5. unicode : 고정 길이 문자열 unicode
> 6. bool : True, False
> 7. string : np.string_

형 변환 세가지 방법
1. np.array(data, dtype=ooo)
2. np.dtype(data)
3. data.astype(dtype)

In [13]:
# 형변환 1. np.array(data, dtype=ooo)

data = [1.5, 2, 3]

a = np.array(data, dtype=np.int32)
print(a.dtype, a, sep='\n')

int32
[1 2 3]


In [14]:
# 형변환 2. np.dtype(data)

data = [1.5, 2, 3]

a = np.int32(a)
print(a.dtype, a, sep='\n')

int32
[1 2 3]


In [15]:
# 형변환 3. data.astype(dtype)

data = [1.5, 2, 3]

a = a.astype(np.int64)
print(a.dtype, a, sep='\n')

int64
[1 2 3]


- uint 자료형(u1, u2, u4, u8)은 부호가 없음을 주의

In [20]:
# unit 자료형
a = np.uint16(0)
a.dtype

dtype('uint16')

In [21]:
# 부호가 나오면 다른 자료형으로 변경
a = a - 1
a.dtype

dtype('int32')

In [228]:
# 음수가 나오면 해당 자료형의 값의 내림차순으로 반환
a = np.uint16(-1)
a

65535

In [229]:
# 16비트의 최댓값은 65536
2**16

65536

---

## 4. 행렬 생성 및 접근
> 1. np.array()
> 2. np.arrange()
> 3. np.linsapace()
> 4. reshape()
> 5. np.ones()
> 6. np.zeros()
> 7. np.eye()
> 8. np.empty()
> 9. np.full()
> 10. np.flatten() / np.ravel()

### 4.1 np.array()

In [245]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 4.2 np.arrange(a, b, n) : a부터 b까지 n의 간격으로 배열 생성

In [247]:
np.arange(1, 5, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### 4.3 np.linspace(a, b, n): a부터 b까지 n개의 등간격 데이터 생성

In [274]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### 4.4 reshape() : ndarray의 차원과 모양을 바꿔준다

In [249]:
# 2차원
a = np.arange(50).reshape(5, 10)
print(a, f'{a.ndim}차원', sep='\n')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
2차원


In [250]:
# 3차원
a = np.arange(50).reshape(2, 5, 5)
print(a, f'{a.ndim}차원', sep='\n')

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]
3차원


In [251]:
# 다차원 ndarray에 접근하는 방법
a[-1][-3][-4] #36
a[1][2][1] #36
a[1,2,1] #36

36

### 4.5 np.ones()

In [257]:
# 1차원
a = np.ones(10)
print(f'{a.ndim}차원', a,  sep='\n')

1차원
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [260]:
# 2차원
a = np.ones([2, 5])
print(f'{a.ndim}차원', a,  sep='\n')

2차원
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [261]:
# 3차원
a = np.ones([3, 4, 5])
print(f'{a.ndim}차원', a,  sep='\n')

3차원
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### 4.6 np.zeros()

In [262]:
# 3차원
a = np.zeros([3, 4, 5])
print(f'{a.ndim}차원', a,  sep='\n')

3차원
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


### 4.7 np.eye() : n x n 사이즈 단위행렬

In [265]:
a = np.eye(3)
print(f'{a.ndim}차원', a,  sep='\n')

2차원
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [267]:
#다차원은 Error
np.eye(3, 3, 3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [271]:
# 단위행렬의 특징 : 단위행렬 * 행렬 A = 행렬 A
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [272]:
e = np.arange(9).reshape(3, 3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [273]:
np.dot(d, e)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

### 4.8 np.empty()

In [28]:
# 메모리에 할당만 맏고 초기화 없이 반환됨
# 때문에 np.zeros()보다 속도가 빠름
np.empty(10)

array([1.45812835e-311, 1.45812865e-311, 1.45812863e-311, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

### 4.9 np.full

In [59]:
np.full((3, 4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

### 4.10 np.flatten() / np.ravel()

In [350]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [351]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [277]:
a.ravel(order='C') #행기준

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [279]:
a.ravel(order='F') #열기준

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

---

## 5. indexcing, slicing

### 5.1 indexcing
- ndarray[start:stop:step]

In [283]:
# ndarray 생성
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [284]:
# 행렬[start:stop:step]
a[5:20:5]

array([ 5, 10, 15])

In [285]:
# 내림차순 정렬 (step 활용)
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

### 5.2 slicing

- 2차원

In [309]:
# ndarray 생성 (2차원)
a = np.arange(30).reshape(5,6)
print(f'{a.ndim}차원', a, sep='\n')

2차원
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [292]:
# 열 슬라이싱
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [293]:
# 행 슬라이싱
a[1, :] # a[1]

array([ 6,  7,  8,  9, 10, 11])

In [294]:
# 행렬의 특정 부분 슬라이싱 1
a[:3, :3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [295]:
# 행렬의 특정 부분 슬라이싱 2
b = a[::2, ::2]
b

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

- 3차원

In [310]:
# ndarray 생성 (3차원)
a = np.arange(30).reshape(2, 5, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [315]:
a[1,:,:]

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [313]:
a[:,1,:]

array([[ 3,  4,  5],
       [18, 19, 20]])

In [314]:
a[:,:,1]

array([[ 1,  4,  7, 10, 13],
       [16, 19, 22, 25, 28]])

In [193]:
a[1,:,::-1]

array([[17, 16, 15],
       [20, 19, 18],
       [23, 22, 21],
       [26, 25, 24],
       [29, 28, 27]])

---

### 6. 얕은 복사, 깊은 복사

### 6.1 얕은 복사

In [297]:
# ndarray 생성
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [298]:
# 행렬의 특정 부분 슬라이싱
b = a[::2, ::2] # 얕은 복사
b

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [299]:
# 요소에 특정 값 할당
b[0] = 100
b[-2][-2] = 200
b

array([[100, 100, 100],
       [ 12, 200,  16],
       [ 24,  26,  28]])

In [300]:
# a에도 영향을 미친다는 것을 주의
a

array([[100,   1, 100,   3, 100,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13, 200,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

### 6.2 깊은 복사

In [302]:
# 깊은 복사
c = a[::2, ::2].copy()
c

array([[100, 100, 100],
       [ 12, 200,  16],
       [ 24,  26,  28]])

In [303]:
# 요소에 특정 값 할당
c[2][2] = 300
c

array([[100, 100, 100],
       [ 12, 200,  16],
       [ 24,  26, 300]])

In [304]:
# 이번에는 원본 데이터에 영향을 미치지 않음
a

array([[100,   1, 100,   3, 100,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13, 200,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

---

## 7. 배열의 연결과 분할

### 7.1 배열의 연결

- 배열의 합

In [318]:
# 배열의 합
a = [1, 2, 3]
b = [4, 5, 6]

np.array(a) + np.array(b)

array([5, 7, 9])

- 배열의 연결 : concatenate

In [319]:
# 배열의 연결
a = np.array(a)
b = np.array(b)

np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [320]:
# 배열의 연결 (차원유지)
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

np.concatenate([a, b]) # 2차원

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [321]:
# 배열의 연결 (차원추가)
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

np.concatenate([[a, b]]) # 3차원

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

- axis = 0 (행방향)
- axis = 1 (열방향)

In [322]:
# 배열의 연결 (axis=0)
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

np.concatenate([[a, b], [a, b]], axis=0)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [323]:
# 배열의 연결 (axis=1)
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

- 배열의 연결 np.vstack() / np.hstack()

In [23]:
# 행의 갯수가 맞아야 한다
a = np.arange(14).reshape(2, 7)
b = np.arange(10, 20).reshape(2, 5)

np.hstack([a, b]) #horizontal stack

array([[ 0,  1,  2,  3,  4,  5,  6, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18, 19]])

In [24]:
# 열의 갯수가 맞아야 한다.
a = np.arange(15).reshape(3, 5)
b = np.arange(10, 20).reshape(2, 5)

np.vstack([a, b]) #vertical stack

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 7.1 배열의 분할

- np.split()

In [337]:
# case 1
a = np.arange(12)
np.split(a, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [338]:
# case 2
a = np.arange(10, 121, 10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [335]:
np.split(a, [3, 5, 9, 10])

[array([10, 20, 30]),
 array([40, 50]),
 array([60, 70, 80, 90]),
 array([100]),
 array([110, 120])]

In [25]:
a = np.arange(10, 121, 10).reshape(3, 4)
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

- np.vsplit()

In [26]:
# case 3
np.vsplit(a, 3)

[array([[10, 20, 30, 40]]),
 array([[50, 60, 70, 80]]),
 array([[ 90, 100, 110, 120]])]

- np.hsplit()

In [27]:
# case 4
np.hsplit(a, 4)

[array([[10],
        [50],
        [90]]),
 array([[ 20],
        [ 60],
        [100]]),
 array([[ 30],
        [ 70],
        [110]]),
 array([[ 40],
        [ 80],
        [120]])]

---

## 8. 유니버셜 함수

### 8.1 벡터화 연산
- 넘파이는 유니버셜 함수로 벡터화 연산이 가능하다   
- 그래서 반복문을 사용하지 않아도 연산을 빠르게 수행할 수 있다.

In [339]:
%%timeit

for i in range(10):
    max(range(1000000))

273 ms ± 23.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [340]:
%%timeit

for i in range(10):
    np.max(np.arange(1000000))

21.6 ms ± 855 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 8.2  np.max() / np.min() / np.sum()

In [354]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 8.2.1 np.max()

In [355]:
# 제일 큰 원소의 값
np.max(a)

11

In [356]:
# 첫번째 요소가 큰 것부터 (axis=0, 행방향)
np.max(a, axis=0)

array([ 8,  9, 10, 11])

In [357]:
# 첫번째 요소가 큰 것부터 (axis=1, 열방향)
np.max(a, axis=1)

array([ 3,  7, 11])

#### 8.2.2 np.min()

In [360]:
# 제일 작은 원소의 값
np.min(a)

0

In [358]:
# 첫번째 요소가 작은 것부터 (axis=0, 행방향)
np.min(a, axis=0)

array([0, 1, 2, 3])

In [361]:
# 첫번째 요소가 작은 것부터 (axis=1, 행방향)
np.min(a, axis=1)

array([0, 4, 8])

#### 8.2.3 np.sum()

In [362]:
# 전체 원소의 합
np.sum(a)

66

In [363]:
# 행방향 합
np.sum(a, axis=0)

array([12, 15, 18, 21])

In [364]:
# 열방향 합
np.sum(a, axis=1)

array([ 6, 22, 38])

---

## 7. 집계 함수
> np.mean() : 평균   
> np.median() : 중앙값   
> np.std() : 표준편차   
> np.var() : 분산   
> np.cumsum() : 누적값   
> np.argmin() / np.argmax() : 위치   

In [372]:
a = np.arange(12).reshape(3, 4)
a[0][0]=100
a

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [373]:
np.mean(a) #평균

13.833333333333334

In [374]:
np.median(a) #중앙값

6.5

In [376]:
np.std(a) #표준편차

26.15604880116431

In [377]:
np.var(a) #분산

684.138888888889

In [378]:
np.sum(a, axis=0) #합(행방향)

array([112,  15,  18,  21])

In [379]:
np.sum(a, axis=1) #합(열방향)

array([106,  22,  38])

In [380]:
np.cumsum(a) #누적값

array([100, 101, 103, 106, 110, 115, 121, 128, 136, 145, 155, 166],
      dtype=int32)

In [382]:
np.min(a) # 최솟값

1

In [381]:
np.argmin(a) #위치(index)

1

In [383]:
np.argmax(a) #위치

0

---

## 8. 필터링
### 8.1 Boolean Indexing
> np.any() : 하나라도 True가 있는가?   
> np.all() : 모두가 True인가?   
> np.sum() : nan이 있으면 nan 반환   
> np.nansum() : 숫자가 아닌 것까지 모두 더함   
> np.isnan() : nan인지 boolean으로 반환   
> np.isnan().sum() : 결측치만 모두 더함   
> np.all() : 모든 요소가 괄호안 조건에 부합하는가   
> np.where() : 괄호안 조건에 해당하는 값의 index 반환 및 값 할당

In [387]:
a = np.arange(12).reshape(3, 4)
a[0][0]=0
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [391]:
np.any([0,0,1,1]) # True인 것이 하나라도 있는가?

True

In [393]:
np.all([0,0,1,1]) # 모두가 True인가?

False

In [394]:
np.nansum([1, 2, 3, 4, 0, 0, np.nan, np.nan]) #숫자가 아닌 것까지 모두 더함

10.0

In [149]:
np.sum([1, 2, 3, 4, 0, 0, np.nan, np.nan]) #더하는 숫자가 nan이면 nan 반환

nan

In [395]:
np.isnan(np.array([1, 2, 3, 4, 0, 0, np.nan, np.nan])) # nan인지 아닌지

array([False, False, False, False, False, False,  True,  True])

In [396]:
np.isnan(np.array([1, 2, 3, 4, 0, 0, np.nan, np.nan])).sum() # 결측치만 모두 더함

2

In [401]:
np.all(a > 5) # 모든 요소가 괄호안 조건에 부합하는가 

False

In [402]:
np.where(a > 5) # 괄호안 조건에 해당하는 값의 index 반환

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [403]:
# 조건에 부합하지 않은 것의 값 할당
np.where(a > 5, a, -100)

array([[-100, -100, -100, -100],
       [-100, -100,    6,    7],
       [   8,    9,   10,   11]])

### 8.2 마스킹

In [404]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [405]:
a > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [406]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11])

In [407]:
a[a > 5] = 1
a

array([[0, 1, 2, 3],
       [4, 5, 1, 1],
       [1, 1, 1, 1]])

In [408]:
a[a != 1]

array([0, 2, 3, 4, 5])

In [409]:
a[~(a == 1)]

array([0, 2, 3, 4, 5])

In [410]:
a[~(a == 1) & (a < 4)]

array([0, 2, 3])

In [411]:
a[~(a == 1) | (a < 4)]

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1, 1, 1])

---

## 9. Broadcast
- 크기가 다른 배열간의 연산 함수를 적용하는 규칙의 집합
    - m*n 행렬과 m*1 벡터간의 연산
    - m*n 행렬과 1*n 벡터간의 연산
    - m*1 행렬과 1*n 벡터간의 연산

In [413]:
# 리스트에서는 동일한 크기의 리스트가 아니면 연산을 하지 못함
[1,2,3] + 1

TypeError: can only concatenate list (not "int") to list

In [414]:
np.array([1, 2, 3]) + 1

array([2, 3, 4])

In [416]:
np.arange(9).reshape(3, 3) + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [418]:
np.arange(27).reshape(3, 3, 3) + np.array([1, 2, 3])

array([[[ 1,  3,  5],
        [ 4,  6,  8],
        [ 7,  9, 11]],

       [[10, 12, 14],
        [13, 15, 17],
        [16, 18, 20]],

       [[19, 21, 23],
        [22, 24, 26],
        [25, 27, 29]]])

---

## 10. random
> r.random() : 0부터 1까지의 부동소수점 숫자를 리턴   
> r.randint(a, b) : a부터 b까지의 임의의 정수를 리턴   
> r.uniform(a, b) : a부터 b까지의 부동소수점 숫자를 리턴   
> r.randn() : 가우시안 표준 정규분포  
> r.randrange(a, b, n) : range(a,b,n)에서 랜덤하게 숫자를 리턴   
> r.shuffle(l) : 안에 있는 요소의 순서를 섞어 리턴   
> r.choice(l) : 안에 있는 요소 중 하나를 리턴   
> r.sample(l,n) : 안에 잇는 요소 중 n개를 리턴
> r.seed() : 시드값 설정   

In [431]:
import random as r

In [432]:
r.randint(1, 10) # 1부터 10까지의 임의의 정수를 리턴

3

In [433]:
r.random() # 0부터 1까지의 부동소수점 숫자를 리턴

0.5692038748222122

In [434]:
r.uniform(1, 10) # 1부터 10까지의 부동소수점 숫자를 리턴

8.220385550513651

In [435]:
r.randrange(1, 10, 2) # range(1,10,2)에서 랜덤하게 숫자를 리턴

1

In [184]:
# 안에 있는 요소의 순서를 섞어 리턴
l = [i for i in range(20)]
r.shuffle(l)
l

[17, 11, 16, 4, 8, 13, 19, 10, 18, 7, 5, 3, 1, 12, 0, 15, 14, 6, 9, 2]

In [185]:
# 안에 있는 요소 중 하나를 리턴
r.choice(l)

17

In [436]:
# 안에 있는 요소 중 5개를 리턴
r.sample(l, 5)

[18, 4, 15, 0, 6]

In [204]:
# seed를 같게 세팅하면 같은 난수가 순서대로 생겨남.
r.seed(1)
r.randint(1, 10)

3

In [209]:
r.seed(1)
r.randint(1, 10)

3

In [427]:
np.random.seed(1)
np.random.randint(1, 10, size=(10))

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5])

In [428]:
np.random.seed(1)
np.random.randint(1, 10, size=(3,4))

array([[6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3]])

In [ ]:
# np.random.randint()
# np.random.normal()
# np.random.uniform()